[project]
name = "llm-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy==1.26.4",
    "pip>=25.0.1",
    "tiktoken>=0.9.0",
    "torch==2.2.2",
]
